RPi-#61. Controller parse control.json
NTUEELightDance/LightDance-RPi pull request #62
Opened 2022-03-09 19:18 UTC by FYRichie

### What is this PR for?

Make controller enable to parse LED.json, OF.json, and light LED and OF.

### What type of PR is it?

[Feature]

### Todos

-   [Debug] -   Task

### What is the Github issue?

https://github.com/NTUEELightDance/LightDance-RPi/issues/61

### How should this be tested?

Currently none

### Screenshots (if appropriate)

None

### Questions:

-   Do the license files need updating? No
-   Are there breaking changes for older versions? Yes Yes Yes
-   Does this need new documentation? Yes

2022-03-09 19:18 UTC, FYRichie commented
@Kenchu123 Don't merge this pr yet.

2022-03-11 17:11 UTC, Kenchu123 requested changes

2022-03-11 17:11 UTC, Kenchu123 commented on test_controller/src/method.cpp
> +    logger->success("Eltest");
This should be OFTest.

2022-03-12 09:11 UTC, Kenchu123 commented
RPi-#61. Controller parse control.json

2022-03-12 09:11 UTC, merged